[package]
name = "bank"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hashbrown = "0.13.1"
thiserror = "1.0.37"
serde_json = "1.0.86"
anyhow = "1.0.66"